name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # This runs the workflow every hour
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check for new Caddy image
        id: check_caddy
        run: |
          # Pull the latest Caddy image
          docker pull caddy:latest
          # Get the image digest
          CADDY_IMAGE=$(docker inspect --format='{{index .RepoDigests 0}}' caddy:latest)
          echo "CADDY_IMAGE=$CADDY_IMAGE" >> $GITHUB_ENV

      - name: Check for changes
        id: check_changes
        run: |
          # Check if the digest has changed
          if [ -f last_digest.txt ]; then
            LAST_DIGEST=$(cat last_digest.txt)
          else
            LAST_DIGEST=""
          fi

          if [ "$CADDY_IMAGE" != "$LAST_DIGEST" ]; then
            echo "New Caddy image detected."
            echo "$CADDY_IMAGE" > last_digest.txt
            echo "new_caddy_image=true" >> $GITHUB_ENV
          else
            echo "No new Caddy image."
            echo "new_caddy_image=false" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: env.new_caddy_image == 'true'
        run: |
          docker build -t edipdi/caddy-cloudflaredns:latest .
          docker push edipdi/caddy-cloudflaredns:latest
