name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # This runs the workflow every hour
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check for new Caddy image
        id: check_caddy
        run: |
          # Pull the latest Caddy image
          docker pull caddy:latest
          # Get the image digest
          CADDY_IMAGE=$(docker inspect --format='{{index .RepoDigests 0}}' caddy:latest)
          echo "CADDY_IMAGE=$CADDY_IMAGE" >> $GITHUB_ENV

      - name: Load previous digest from the repository
        id: load_digest
        run: |
          # Check if the digest file exists and read it, or set it to empty if not
          if [ -f .caddy-digest1.txt ]; then
            DIGEST_CADDY_CACHE=$(cat .caddy-digest1.txt)
          else
            DIGEST_CADDY_CACHE=""
          fi
          echo "Previous digest: $DIGEST_CADDY_CACHE"
          echo "DIGEST_CADDY_CACHE=$DIGEST_CADDY_CACHE" >> $GITHUB_ENV

      - name: Check for changes
        id: check_changes
        run: |
          # Compare the current digest to the previous one
          if [ "$CADDY_IMAGE" != "$DIGEST_CADDY_CACHE" ]; then
            echo "New Caddy image detected."
            # Update the digest file
            echo "$CADDY_IMAGE" > .caddy-digest1.txt
            echo "new_caddy_image=true" >> $GITHUB_ENV
          else
            echo "No new Caddy image."
            echo "new_caddy_image=false" >> $GITHUB_ENV
          fi

      - name: Commit updated digest file to the repository
        if: env.new_caddy_image == 'true'
        run: |
          # Configure Git user for GitHub Actions
          git config --local user.name "GitHub Actions"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the updated digest file to git
          git add .caddy-digest1.txt
          
          # Commit the updated digest
          git commit -m "Update Caddy image digest"
          
          # Push the changes using the GitHub Actions token for authentication
          git push https://x-access-token:${{ secrets.PAT_TOKE }}@github.com/${{ github.repository }} HEAD:main

      - name: Build and push Docker image
        if: env.new_caddy_image == 'true'
        run: |
          docker build -t edipdi/caddy-cloudflaredns:latest .
          docker push edipdi/caddy-cloudflaredns:latest
